"""
Saraswati (सरस्वती): The Goddess of Knowledge / Skill Learning.

Named after the Hindu goddess of learning, music, and wisdom.
Saraswati observes repeated patterns in conversations and autonomously
generates new skills, validates them, and deploys them.

Pipeline:
  Shruti (observation) → Smriti (codification) → Vidya (validation + deployment)

Saraswati itself is a BreathTask that runs the full pipeline between conversations.
"""

from __future__ import annotations

import ast
import json
import importlib.util
import sys
import textwrap
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

from loguru import logger

from velvet.shen.xi import BreathTask, ComputeBudget, ConversationTurn


# ============================================================================
# Data Models
# ============================================================================

@dataclass
class WorkflowCandidate:
    """A potential workflow pattern detected by Shruti."""
    description: str           # What the user was trying to do
    trigger_phrases: list[str] # Example phrases that trigger this workflow
    steps: list[str]           # Ordered list of steps
    skill_name: str = ""       # Suggested skill name (snake_case)
    frequency: int = 1         # How many times this pattern was seen
    confidence: float = 0.0    # LLM confidence (0-1)


@dataclass
class GeneratedSkill:
    """A skill generated by Smriti."""
    name: str                  # Skill name
    code: str                  # Python source code
    description: str           # Human-readable description
    candidate: WorkflowCandidate = None  # Source candidate


# ============================================================================
# Shruti — The Listener / Pattern Observer
# ============================================================================

class Shruti:
    """
    Shruti (श्रुति): That Which Is Heard.

    Observes conversation batches for repeated patterns and identifies
    workflow candidates — things the user does frequently that could
    become skills.
    """

    async def observe(self, batch: list[ConversationTurn]) -> list[WorkflowCandidate]:
        """
        Analyze a batch of conversation turns for repeated patterns.

        Uses LLM to identify workflow candidates.
        Returns empty list if batch is too small or no patterns found.
        """
        if len(batch) < 3:
            return []

        try:
            from velvet.llm import get_llm_adapter
            adapter = get_llm_adapter()

            # Format the batch for the LLM
            transcript = "\n".join(
                f"User: {t.user_input}\nVelvet: {t.response}"
                for t in batch
            )

            prompt = (
                "Analyze this conversation transcript for REPEATED patterns — "
                "things the user does frequently that could be automated as a skill.\n\n"
                f"Transcript:\n{transcript}\n\n"
                "For each pattern found, output a JSON object with:\n"
                '- "description": what the user is trying to do\n'
                '- "trigger_phrases": list of example phrases\n'
                '- "steps": ordered list of steps\n'
                '- "skill_name": suggested snake_case name\n'
                '- "frequency": how many times this pattern appeared\n'
                '- "confidence": 0-1 confidence score\n\n'
                "Output a JSON array of patterns. If no patterns found, output [].\n"
                "ONLY output valid JSON, nothing else."
            )

            response = await adapter.generate(prompt, max_tokens=500)
            return self._parse_candidates(response)
        except ImportError:
            logger.warning("[Shruti] LLM adapter not available")
            return []
        except Exception as e:
            logger.error(f"[Shruti] Observation failed: {e}")
            return []

    def _parse_candidates(self, response: str) -> list[WorkflowCandidate]:
        """Parse LLM response into WorkflowCandidates."""
        import json
        try:
            # Try to extract JSON from the response
            text = response.strip()
            # Handle markdown code blocks
            if "```" in text:
                text = text.split("```")[1]
                if text.startswith("json"):
                    text = text[4:]
                text = text.strip()

            data = json.loads(text)
            if not isinstance(data, list):
                data = [data]

            candidates = []
            for item in data:
                if isinstance(item, dict):
                    candidates.append(WorkflowCandidate(
                        description=item.get("description", ""),
                        trigger_phrases=item.get("trigger_phrases", []),
                        steps=item.get("steps", []),
                        skill_name=item.get("skill_name", ""),
                        frequency=item.get("frequency", 1),
                        confidence=item.get("confidence", 0.0),
                    ))
            return candidates
        except (json.JSONDecodeError, KeyError, TypeError) as e:
            logger.warning(f"[Shruti] Failed to parse LLM response: {e}")
            return []


# ============================================================================
# Smriti — The Remembered / Code Generator
# ============================================================================

class Smriti:
    """
    Smriti (स्मृति): That Which Is Remembered.

    Takes workflow candidates and generates Python skill code
    using the Velvet @skill decorator pattern.
    """

    async def codify(self, candidate: WorkflowCandidate) -> GeneratedSkill | None:
        """
        Generate Python skill code from a workflow candidate.

        Uses LLM to generate the code, with the @skill decorator pattern.
        """
        if not candidate.skill_name:
            return None

        try:
            from velvet.llm import get_llm_adapter
            adapter = get_llm_adapter()

            prompt = (
                "Generate a Python skill for the Velvet AI assistant.\n\n"
                f"Skill name: {candidate.skill_name}\n"
                f"Description: {candidate.description}\n"
                f"Trigger phrases: {candidate.trigger_phrases}\n"
                f"Steps: {candidate.steps}\n\n"
                "Use this EXACT decorator pattern:\n\n"
                "```python\n"
                "from velvet.skills import skill, SkillCategory, SkillParameter, SkillResult\n\n"
                "@skill(\n"
                '    name="skill_name",\n'
                '    description="What the skill does",\n'
                "    category=SkillCategory.DIGITAL,\n"
                "    parameters=[],\n"
                '    tags=["tag1"],\n'
                ")\n"
                "async def skill_name(**params) -> SkillResult:\n"
                '    return SkillResult.ok(speak="Done!")\n'
                "```\n\n"
                "Rules:\n"
                "- Only use stdlib imports (os, datetime, json, re, pathlib)\n"
                "- No subprocess, eval, exec, or __import__\n"
                "- No network calls (requests, urllib, httpx, aiohttp)\n"
                "- Keep the code simple and safe\n"
                "- Return SkillResult.ok() or SkillResult.fail()\n\n"
                "Output ONLY the Python code, no explanation."
            )

            response = await adapter.generate(prompt, max_tokens=500)
            code = self._extract_code(response)

            if code:
                return GeneratedSkill(
                    name=candidate.skill_name,
                    code=code,
                    description=candidate.description,
                    candidate=candidate,
                )
            return None
        except ImportError:
            logger.warning("[Smriti] LLM adapter not available")
            return None
        except Exception as e:
            logger.error(f"[Smriti] Code generation failed: {e}")
            return None

    def _extract_code(self, response: str) -> str:
        """Extract Python code from LLM response."""
        text = response.strip()

        # Handle markdown code blocks
        if "```python" in text:
            parts = text.split("```python")
            if len(parts) > 1:
                code = parts[1].split("```")[0].strip()
                return code
        elif "```" in text:
            parts = text.split("```")
            if len(parts) > 1:
                code = parts[1].strip()
                if code.startswith("python"):
                    code = code[6:].strip()
                return code

        # No code block — assume the entire response is code
        if "from velvet" in text or "@skill" in text or "import " in text:
            return text

        return ""


# ============================================================================
# Vidya — The Knowledge / AST Validator + Deployer
# ============================================================================

# Safety: banned function calls and modules
BANNED_CALLS = {
    "eval", "exec", "compile", "__import__", "globals", "locals",
    "getattr", "setattr", "delattr", "open",  # open is risky for generated code
}

BANNED_IMPORTS = {
    "subprocess", "os.system", "shutil", "ctypes",
    "requests", "urllib", "httpx", "aiohttp", "socket",
    "pickle", "shelve", "marshal",
}

ALLOWED_IMPORTS = {
    "velvet.skills", "os", "os.path", "datetime", "json", "re",
    "pathlib", "math", "random", "string", "collections",
    "itertools", "functools", "typing", "enum", "dataclasses",
}


class Vidya:
    """
    Vidya (विद्या): Knowledge / Discriminating Wisdom.

    Validates generated skill code using AST analysis and deploys
    safe skills to the skills directory for hot-loading.
    """

    def __init__(self, skills_dir: str | Path | None = None):
        if skills_dir is None:
            skills_dir = Path.home() / ".velvet" / "skills"
        self._skills_dir = Path(skills_dir)

    def validate(self, skill: GeneratedSkill) -> tuple[bool, list[str]]:
        """
        Validate a generated skill using AST analysis.

        Returns (is_safe, list_of_violations).
        """
        violations = []

        try:
            tree = ast.parse(skill.code)
        except SyntaxError as e:
            return False, [f"Syntax error: {e}"]

        for node in ast.walk(tree):
            # Check function calls
            if isinstance(node, ast.Call):
                func_name = self._get_call_name(node)
                if func_name and func_name in BANNED_CALLS:
                    violations.append(f"Banned call: {func_name}()")

            # Check imports
            if isinstance(node, ast.Import):
                for alias in node.names:
                    if not self._is_allowed_import(alias.name):
                        violations.append(f"Banned import: {alias.name}")

            if isinstance(node, ast.ImportFrom):
                module = node.module or ""
                if not self._is_allowed_import(module):
                    violations.append(f"Banned import: from {module}")

        is_safe = len(violations) == 0
        return is_safe, violations

    def deploy(self, skill: GeneratedSkill) -> bool:
        """
        Deploy a validated skill to the skills directory for hot-loading.

        Creates a .py file in ~/.velvet/skills/ and imports it to register.
        """
        self._skills_dir.mkdir(parents=True, exist_ok=True)
        file_path = self._skills_dir / f"{skill.name}.py"

        try:
            # Write the skill file
            file_path.write_text(skill.code, encoding="utf-8")
            logger.info(f"[Vidya] Deployed skill file: {file_path}")

            # Hot-load: import the module to trigger @skill registration
            self._hot_load(skill.name, file_path)
            return True
        except Exception as e:
            logger.error(f"[Vidya] Deployment failed: {e}")
            return False

    def _hot_load(self, name: str, path: Path):
        """Import a skill module dynamically to register it."""
        module_name = f"velvet_learned_skill_{name}"
        try:
            spec = importlib.util.spec_from_file_location(module_name, str(path))
            if spec and spec.loader:
                module = importlib.util.module_from_spec(spec)
                sys.modules[module_name] = module
                spec.loader.exec_module(module)
                logger.info(f"[Vidya] Hot-loaded skill: {name}")
        except Exception as e:
            logger.error(f"[Vidya] Hot-load failed for {name}: {e}")

    @staticmethod
    def _get_call_name(node: ast.Call) -> str | None:
        """Extract function name from a Call node."""
        if isinstance(node.func, ast.Name):
            return node.func.id
        elif isinstance(node.func, ast.Attribute):
            return node.func.attr
        return None

    @staticmethod
    def _is_allowed_import(module: str) -> bool:
        """Check if an import is in the allowed list."""
        for allowed in ALLOWED_IMPORTS:
            if module == allowed or module.startswith(allowed + "."):
                return True
        return False


# ============================================================================
# Saraswati — The Orchestrator / BreathTask
# ============================================================================

class Saraswati(BreathTask):
    """
    Saraswati (सरस्वती): Skill Learning BreathTask.

    Orchestrates the full pipeline:
    1. Shruti observes conversation patterns
    2. Smriti generates skill code from promising patterns
    3. Vidya validates (AST safety) and deploys

    Only processes candidates with confidence >= 0.7 and frequency >= 3.
    """

    def __init__(self, trust_engine=None, skills_dir: str | Path | None = None):
        self._shruti = Shruti()
        self._smriti = Smriti()
        self._vidya = Vidya(skills_dir=skills_dir)
        self._trust = trust_engine
        self._min_confidence = 0.7
        self._min_frequency = 3
        
        # Path for pending skills
        from velvet.config import get_config
        cfg = get_config()
        self._pending_file = Path(cfg.storage.data_dir) / "pending_skills.json"

    def name(self) -> str:
        return "saraswati"

    def budget(self) -> ComputeBudget:
        return ComputeBudget(
            cpu_seconds=5.0,
            gpu_needed=False,
            gpu_vram_mb=0,
            ram_mb=128,
            network_io=False,
            priority=9,  # Lowest priority — runs last
        )

    async def run(self, batch: list[ConversationTurn]) -> None:
        """Run the full skill learning pipeline."""
        if len(batch) < 3:
            return

        # 1. Observe patterns
        candidates = await self._shruti.observe(batch)
        if not candidates:
            logger.debug("[Saraswati] No workflow candidates found")
            return

        # 2. Filter by quality
        promising = [
            c for c in candidates
            if c.confidence >= self._min_confidence and c.frequency >= self._min_frequency
        ]
        if not promising:
            logger.debug(
                f"[Saraswati] {len(candidates)} candidates found but none meet "
                f"thresholds (conf>={self._min_confidence}, freq>={self._min_frequency})"
            )
            return

        logger.info(f"[Saraswati] {len(promising)} promising candidates, generating skills...")

        # 3. Generate and validate each
        for candidate in promising:
            try:
                # Generate code
                skill = await self._smriti.codify(candidate)
                if not skill:
                    continue

                # Validate AST safety
                is_safe, violations = self._vidya.validate(skill)
                if not is_safe:
                    logger.warning(
                        f"[Saraswati] Skill '{skill.name}' failed validation: {violations}"
                    )
                    continue

                # Trust check (optional)
                if self._trust and self._trust.should_ask("skill_learning", skill.name):
                    logger.info(
                        f"[Saraswati] Skill '{skill.name}' needs user approval "
                        f"(trust check). Queuing for review."
                    )
                    await self._queue_for_approval(skill)
                    continue

                # Deploy
                deployed = self._vidya.deploy(skill)
                if deployed:
                    logger.info(f"[Saraswati] 🎓 Learned new skill: {skill.name}")
                else:
                    logger.error(f"[Saraswati] Failed to deploy skill: {skill.name}")

            except Exception as e:
                logger.error(f"[Saraswati] Pipeline error for '{candidate.skill_name}': {e}")

    async def _queue_for_approval(self, skill: GeneratedSkill):
        """Queue a validated skill for user approval and notify."""
        try:
            # 1. Load existing pending skills
            pending = {}
            if self._pending_file.exists():
                try:
                    pending = json.loads(self._pending_file.read_text())
                except Exception:
                    pass
            
            # 2. Add/Update skill
            pending[skill.name] = {
                "name": skill.name,
                "description": skill.description,
                "code": skill.code,
                "timestamp": json.dumps(json.dumps("")) # Just a placeholder for now
            }
            # Fix timestamp
            from datetime import datetime, timezone
            pending[skill.name]["timestamp"] = datetime.now(timezone.utc).isoformat()
            
            # 3. Save
            self._pending_file.write_text(json.dumps(pending, indent=2))
            logger.info(f"[Saraswati] Skill '{skill.name}' queued for approval in {self._pending_file}")
            
            # 4. Notify via Fabric
            from velvet.fabric import get_fabric
            fabric = get_fabric()
            
            # Announce via TTS (as if Velvet is speaking)
            notify_payload = {
                "text": f"Velvet: I have learned a new potential skill called {skill.name}. Should I add it to my capabilities?",
                "skill_name": skill.name,
                "requires_approval": True
            }
            await fabric.publish("velvet/mesh/notify", notify_payload)
            
        except Exception as e:
            logger.error(f"[Saraswati] Failed to queue skill {skill.name}: {e}")
